download:
  download_ttl: 15
indexing:
  dirs:
  - C:\\Users\\storm\\OneDrive\\Pulpit
  - C:\\Users\\solic\\Documents\\PDF
  file_types:
  - docx
  - pdf
  - epub
  - txt
  - odt
  - rtf
  - md
  metadata: true
network:
  type: peerOnly
